// src/components/Presentation.tsx
import { HTMLAttributes, HTMLProps } from "react";
import styled from "styled-components";
import { Socials } from "./Socials";

const Section = styled.section`
  width: 100%;
  display: grid;
  grid-template-columns: 1fr auto;
  align-items: center;
`;

const Container = styled.div`
  color: #eeeeee;
  display: grid;
  gap: 1rem;

  h1 {
    font-size: 3rem;
    line-height: 2rem;
  }

  p {
    font-weight: 300;
    font-size: 1.125rem;
  }

  a {
    line-height: 2.5rem;
    height: 2.5rem;
    width: 9rem;
    border-radius: 1.25rem;
    background: #375c86;
    color: #eeeeee;
    font-weight: 300;
    font-size: 1.125rem;
    text-decoration: none;
    text-align: center;
    cursor: pointer;
    transition: all 0.15s linear;
    &:hover {
      background: #3e6897;
    }
  }

  @media (max-width: 648px) {
    h1 {
      font-size: 2.25rem;
      line-height: 1.5rem;
    }

    p {
      font-size: 1rem;
    }

    a {
      line-height: 2rem;
      height: 2rem;
      width: 7.5rem;
      border-radius: 1rem;
      font-size: 1rem;
    }
  }
`;

export function Presentation(props: HTMLAttributes<HTMLBaseElement>) {
  return (
    <Section {...props}>
      <Container>
        <h1>José Anselmo</h1>
        <p>Desenvolvedor fullstack</p>
        <a href="#about-me">Sobre mim</a>
      </Container>
      <Socials />
    </Section>
  );
}

// components/organisms/Presentation.vue
<template>
  <section class="presentation">
    <div class="presentation-text">
      <h1>José Anselmo</h1>
      <p>Desenvolvedor fullstack</p>
      <a href="#about-me" class="about-me">Sobre mim</a>
    </div>
    <Socials />
  </section>
</template>

<style lang="scss" scoped>
.presentation {
  margin-left: 5rem;
  align-self: center;
  display: grid;
  grid-template-columns: auto 4rem;
  justify-items: space-between;
  align-items: center;
  h1 {
    font-size: 5.625rem;
    margin: 0;
  }
  p {
    margin: 0;
    font-size: 1.875rem;
    font-weight: 300;
  }
  .about-me {
    width: 12.5rem;
    height: 3.75rem;
    background: color("primary");
    color: white;
    text-decoration: none;
    display: grid;
    align-items: center;
    justify-items: center;
    border-radius: 1.875rem;
    font-size: 1.875rem;
    font-weight: 300;
    margin-top: 1.25rem;
    &:hover {
      background: color("primary", "lighter");
    }
  }
  @include screen("large") {
    margin-left: 4rem;
    .presentation-text {
      h1 {
        font-size: 4.5rem;
      }
      p {
        font-size: 1.25rem;
      }
      .about-me {
        width: 10rem;
        height: 3rem;
        border-radius: 1.5rem;
        font-size: 1.25rem;
      }
    }
  }
  @include screen("medium") {
    margin-left: 3.2rem;
    .presentation-text {
      h1 {
        font-size: 3.6rem;
      }
      p {
        font-size: 1rem;
      }
      .about-me {
        width: 8rem;
        height: 2.4rem;
        border-radius: 1.2rem;
        font-size: 1rem;
        margin-top: 0.75rem;
      }
    }
  }
  @include screen("small") {
    margin-left: 2.56rem;
    .presentation-text {
      h1 {
        font-size: 2.88rem;
      }
      p {
        font-size: 1rem;
      }
      .about-me {
        width: 8rem;
        height: 2.4rem;
        border-radius: 1.2rem;
        font-size: 1rem;
      }
    }
  }
}
</style>
